### ISSUE TITLE
Code review for the day planner project

### ISSUE THREAD

**Issue by SergeiObolevich** [TsyPolina/DayPlanner#1]
In general, your code is clear. But to see the full picture of the project, I need to know the scope of use and carefully review the business requirements.
Also there are some issues :

in CurrentTaskAdapter.java
row 26: Space in this place is extra

in DoneTaskAdapter.java
row 28: Space in this place is extra

in TabAdapter.java
row 40: Space in this place is extra

in TaskAdapter.java
row 139: Space in this place is extra

in AlarmSetter.java
row 32: Space in this place is extra

in TimePickerFragment.java
row 29: Space in this place is extra

Errors affecting the performance of the application, I did not find. The code is written adhering to one style.

**Comment by TsyPolina** [comment]
Thank you for review. All notes will be fixed.
